In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

In [29]:
#Q1
df=sns.load_dataset('taxis')
df.head()

pickup             dropoff  passengers  distance  fare   tip  \
0 2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0  2.15   
1 2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0  0.00   
2 2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5  2.36   
3 2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0  6.15   
4 2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0  1.10   

   tolls  total   color      payment            pickup_zone  \
0    0.0  12.95  yellow  credit card        Lenox Hill West   
1    0.0   9.30  yellow         cash  Upper West Side South   
2    0.0  14.16  yellow  credit card          Alphabet City   
3    0.0  36.95  yellow  credit card              Hudson Sq   
4    0.0  13.40  yellow  credit card           Midtown East   

            dropoff_zone pickup_borough dropoff_borough  
0    UN/Turtle Bay South      Manhattan       Manhattan  
1  Upper West Side South      Manhattan       Manhattan  
2           West Village      Manhattan       Manhattan  
3         Yorkville West      Manhattan       Manhattan  
4         Yorkville West      Manhattan       Manhattan

In [68]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
scaler=MinMaxScaler()

In [7]:
scaler.fit_transform(df[['fare']]) #Min Max scale is used to process data and tranform the value between 0-1

array([[0.04026846],
       [0.02684564],
       [0.04362416],
       ...,
       [0.10067114],
       [0.03355705],
       [0.09395973]])

In [12]:
#Q2
#unit Vector converts the data so that distance between is equivalent to 1.

In [10]:
from sklearn.preprocessing import normalize

In [11]:
pd.DataFrame(normalize(df[['distance','fare','tip']]),columns=['distance','fare','tip'])

distance      fare       tip
0     0.213461  0.933894  0.286839
1     0.156064  0.987747  0.000000
2     0.171657  0.939731  0.295702
3     0.267899  0.939386  0.213971
4     0.231742  0.965592  0.118017
...        ...       ...       ...
6428  0.160133  0.960800  0.226322
6429  0.307453  0.951563  0.000000
6430  0.250500  0.968117  0.000000
6431  0.183497  0.983020  0.000000
6432  0.242956  0.946580  0.212034

[6433 rows x 3 columns]

In [13]:
#Q3

In [15]:
# Principal component analysis, or PCA, is a statistical procedure that allows you to summarize the information content in large data tables by means of a smaller set of “summary indices” that can be more easily visualized and analyzed.

In [34]:

from sklearn.decomposition import PCA
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
pca = PCA(n_components=2)


In [32]:
pca.fit_transform(X)
print(pca.explained_variance_ratio_)
print(pca.singular_values_)


[0.99244289 0.00755711]
[6.30061232 0.54980396]


In [25]:
#Q4

In [27]:
# PCA performs a linear transformation of data, seeking directions of maximum variance. Feature Selection: Principal components are ranked by the variance they explain, allowing for effective feature selection

In [37]:
#Example
pca.fit_transform(df[['fare','distance']])


array([[-6.23989792, -0.4408769 ],
       [-8.38999578, -0.25872541],
       [-5.83030713, -0.07326924],
       ...,
       [ 3.10868303, -0.2050076 ],
       [-7.33713188, -0.27815742],
       [ 2.06765114, -0.22378558]])

In [36]:
print(pca.explained_variance_ratio_)
print(pca.singular_values_)

[0.98613187 0.01386813]
[969.19971217 114.9356272 ]


In [52]:
#q5
df=pd.DataFrame({'Price':[434,123,156,283,383],
                'Rating':[1,3,4,4,2],
                'Delivery Time':[5,8,10,9,6]})

In [53]:
df.head()

Price  Rating  Delivery Time
0    434       1              5
1    123       3              8
2    156       4             10
3    283       4              9
4    383       2              6

In [54]:
scaler=MinMaxScaler()

In [55]:
df1=pd.DataFrame(scaler.fit_transform(df[['Price','Rating','Delivery Time']]),columns=['Price1','Rating1','Delivery Time1'])

In [62]:
pd.concat([df,df1],axis=1)

Price  Rating  Delivery Time    Price1   Rating1  Delivery Time1
0    434       1              5  1.000000  0.000000             0.0
1    123       3              8  0.000000  0.666667             0.6
2    156       4             10  0.106109  1.000000             1.0
3    283       4              9  0.514469  1.000000             0.8
4    383       2              6  0.836013  0.333333             0.2

In [63]:
# Q6
# We can use PCA to do a linear transformation of the data based upon a Domain Expert Advice to minimise loss of data on important features in the Stock market.
# We can use the follwing library for PCA from sklearn.decomposition import PCA 
# We can use the n_features to select the features required and perform the operation and thereafter Principal components are ranked by the variance they explain, allowing for effective feature selection


In [64]:
#Q7

In [78]:
x=np.array([1, 5, 10, 15, 20])
df=pd.DataFrame(x,columns=['Values'])

In [69]:
scaler=MinMaxScaler()

In [79]:
scaler.fit_transform(df[['Values']])

array([[0.        ],
       [0.21052632],
       [0.47368421],
       [0.73684211],
       [1.        ]])

In [6]:
#8
df=pd.DataFrame({'height':[125,153,145,168,180],
              'weight':[74,68,90,83,88],
              'age':[22,35,60,17,19],
              'gender':['M','F','M',"F",'M'], 
              'blood pressure':[116,120,140,135,125]})

In [7]:
df

height  weight  age gender  blood pressure
0     125      74   22      M             116
1     153      68   35      F             120
2     145      90   60      M             140
3     168      83   17      F             135
4     180      88   19      M             125

In [17]:
#Q8
from sklearn.decomposition import PCA

In [13]:
pca=PCA(n_components=4)

In [14]:
pca.fit_transform(df[['height', 'weight', 'age', 'blood pressure']])

array([[-23.04421382, -23.07582093,  -5.34986775,  -1.85731338],
       [ -5.25748164,  -4.96159892,  13.21390791,   2.12933338],
       [-19.65448572,  28.44199162,  -2.3436263 ,  -0.67949938],
       [ 19.17471306,  -1.33314745,  -6.14268059,   5.90089586],
       [ 28.78146811,   0.92857568,   0.62226673,  -5.49341648]])

In [15]:
print(pca.explained_variance_ratio_)
print(pca.singular_values_)

[0.5590126  0.35736224 0.06444929 0.01917587]
[46.27113831 36.99591055 15.71116712  8.56992355]


In [16]:
#We can now rank the Features as per the Variance for Feature Selection