In [1]:
#q1

In [2]:
# In machine learning, the polynomial kernel is a kernel function commonly used with support vector machines 
# (SVMs) and other kernelized models, that represents the similarity of vectors (training samples) in a feature 
# space over polynomials of the original variables, allowing learning of non-linear models.

In [3]:
#q2

In [6]:
# Steps SVM Poly Kernel algorithm.
# from sklearn.metrics import accuracy_score.
# from svm2 import SVM.
# svm = SVM(kernel="poly")
# w, b, losses = svm. fit(X_train, y_train)
# pred = svm. predict(X_test)
# Accuracy: 0.7657142857142857.

In [7]:
#q3

In [8]:
# Parameter ε controls the width of the ε-insensitive zone, used to fit the training data. 
# The value of ε can affect the number of support vectors used to construct the regression function. 
# The bigger ε, the fewer support vectors are selected. On the other hand, bigger ε-values results in more 
# flat estimates.

In [9]:
#q4

In [1]:
# C: float, default=1.0
# Regularization parameter. The strength of the regularization is inversely proportional to C. Must be strictly positive. The penalty is a squared l2 penalty.

In [2]:
# Intuitively, the gamma parameter defines how far the influence of a single training example reaches, with low values meaning 'far' and high values meaning 'close'

In [3]:
 # a linear kernel should be used if the data is linearly separable or has many features, 
 #    a polynomial kernel if it has nonlinear patterns or interactions between features, 
 #    an RBF kernel if it has complex and nonlinear patterns or clusters, and 
 #    a sigmoid kernel if it is binary or looks like a logistic function

In [4]:
# The value of ϵ defines a margin of tolerance where no penalty is given to errors. Remember the support vectors
# are the instances across the margin, i.e. the samples being penalized, which slack variables are non-zero. The
# larger ϵ is, the larger errors you admit in your solution.

In [5]:
#Q5

In [7]:

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
from sklearn.datasets import load_breast_cancer

In [12]:
dataset=load_breast_cancer()

In [13]:
dataset.DESCR

'.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.  For inst

In [21]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [24]:
df['target']=dataset.target


In [41]:
df['target'].unique()

array([0, 1])

In [25]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [35]:
from sklearn.preprocessing import StandardScaler

In [39]:
scaler=StandardScaler()
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [42]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [43]:
from sklearn.svm import SVC

In [44]:
svc=SVC()

In [45]:
svc.fit(X_train,y_train)

SVC()

In [46]:
y_pred=svc.predict(X_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1])

In [47]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [48]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.89      0.93        54
           1       0.94      0.99      0.96        89

    accuracy                           0.95       143
   macro avg       0.96      0.94      0.95       143
weighted avg       0.95      0.95      0.95       143

[[48  6]
 [ 1 88]]
0.951048951048951


In [49]:
from sklearn.model_selection import GridSearchCV
 
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel':['linear']
              }

In [50]:
grid=GridSearchCV(SVC(),param_grid=param_grid,refit=True,cv=4,verbose=3)

In [51]:
grid.fit(grid.fit(X_train,y_train))

Fitting 4 folds for each of 25 candidates, totalling 100 fits
[CV 1/4] END .....C=0.1, gamma=1, kernel=linear;, score=0.953 total time=   0.2s
[CV 2/4] END .....C=0.1, gamma=1, kernel=linear;, score=0.953 total time=   0.2s
[CV 3/4] END .....C=0.1, gamma=1, kernel=linear;, score=0.972 total time=   0.1s
[CV 4/4] END .....C=0.1, gamma=1, kernel=linear;, score=0.906 total time=   0.1s
[CV 1/4] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.953 total time=   0.2s
[CV 2/4] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.953 total time=   0.2s
[CV 3/4] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.972 total time=   0.1s
[CV 4/4] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.906 total time=   0.1s
[CV 1/4] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.953 total time=   0.2s
[CV 2/4] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.953 total time=   0.2s
[CV 3/4] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.972 total time=   0.1s
[CV 4/4] END ..C=0.1, gamma=0.01, kernel=linear

TypeError: Singleton array array(GridSearchCV(cv=4, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']},
             verbose=3), dtype=object) cannot be considered a valid collection.

In [52]:
grid.best_params_

{'C': 1000, 'gamma': 1, 'kernel': 'linear'}

In [53]:
## Prediction
y_pred4=grid.predict(X_test)
print(classification_report(y_test,y_pred4))
print(confusion_matrix(y_test,y_pred4))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.93      0.93        54
           1       0.96      0.97      0.96        89

    accuracy                           0.95       143
   macro avg       0.95      0.95      0.95       143
weighted avg       0.95      0.95      0.95       143

[[50  4]
 [ 3 86]]
0.951048951048951
